name: reverse-proxy

services:
  reverse-proxy-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "8080:8080"
      - "80:80"
    networks: # Corrected 'networks_node' to 'networks'
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Added space after '-'
      - .:/app # Added space after '-'

networks:
  bridge:
    driver: bridge
